### ISSUE TITLE
Unable to remove codeblock using backspace

### ISSUE THREAD

**Issue by RobertBoes** [muc-dev/linked#24]
Platform: Windows
Version: 1.1.3

-----

For an empty day, click on code-block. The first (and only) line is now a code-block. I would expect backspace to remove the code-block to revert to normal text.
It seems now the only way to remove the code-block would be to do the following: Go to a new line using `ctrl` + `enter`, put the cursor inside the code-block again and press delete. Or, go to a new line using `ctrl` + `enter`, then press backspace to delete the code-block.

It does work correctly when the code-block is not on the first line

**Comment by RobertBoes** [comment]
Somehow I didn't notice tiptap is used and apparently it's a bug in tiptap, see ueberdosis/tiptap#856

**Comment by lostdesign** [comment]
Thanks for your report @RobertBoes. I do have noticed that as well, but as you've already seen, it's a "bug" in tiptap which I also addressed in V2 of tiptap, as that is what linked uses. I've tried to reproduce the bug in a v2 sandbox to be sure it's not my implementation, but it indeed still exists there. 

Using a static/fixed menubar would be a workaround, as you can click on the codeblock formatting again to remove it - or as you described, using cmd/ctrl+enter to leave the codeblock to then delete it. I hope this gets resolved soon.

See https://next.tiptap.dev/

**Comment by lostdesign** [comment]
@RobertBoes it was just fixed in tiptap-next. I'll go ahead and upgrade the editor the coming days.

**Comment by lostdesign** [comment]
Had been fixed, totes forgot to close this issue!

**Comment by lostdesign** [comment]
Wait no, 1.1.4 has not been deployed yet. Hold on....
