### ISSUE TITLE
add support for audio recording

### ISSUE THREAD

**Issue by mwager** [muc-dev/linked#8]
more info soon!

**Comment by mwager** [comment]
Problem: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia
-> deprecated. 👎 

Also:

_navigator.mediaDevices.getUserMedia does not work on macOS for audio capture due to a fundamental limitation whereby apps that want to access the system's audio require a signed kernel extension. Chromium, and by extension Electron, does not provide this._

SRC: https://www.electronjs.org/docs/api/desktop-capturer

**Comment by lostdesign** [comment]
Just dumping my research results here:
https://developer.chrome.com/docs/extensions/reference/tabCapture/
https://github.com/electron/electron/issues/4776
https://github.com/electron/electron/issues/10515
https://github.com/Streampunk/naudiodon
